// function generateReport() {

//   const company = document.getElementById("company").value.trim();
//   const industry = document.getElementById("industry").value.trim();

//   const q1 = document.getElementById("q1").value.trim().toLowerCase();
//   const q2 = document.getElementById("q2").value.trim().toLowerCase();
//   const q3 = document.getElementById("q3").value.trim().toLowerCase();
//   const q4 = document.getElementById("q4").value.trim().toLowerCase();

//   if (!company || !industry || !q1 || !q2 || !q3 || !q4) {
//     alert("⚠️ Please fill all fields before generating the report.");
//     return;
//   }

//   document.getElementById("output").innerText = "🔍 Analyzing your IT environment...";

//   setTimeout(() => {

//     let risks = [];
//     let recommendations = [];
//     let score = 0;

//     // Access Control
//     if (q1.includes("no") || q1.includes("basic")) {
//       risks.push("Weak or missing access control mechanisms");
//       recommendations.push("Implement Role-Based Access Control (RBAC)");
//     } else {
//       score += 1;
//     }

//     // MFA
//     if (q2.includes("no")) {
//       risks.push("Lack of Multi-Factor Authentication");
//       recommendations.push("Enable MFA for all critical systems");
//     } else {
//       score += 1;
//     }

//     // Audits
//     if (q3.includes("no") || q3.includes("rare")) {
//       risks.push("Inconsistent or отсутствing audit practices");
//       recommendations.push("Conduct periodic internal and external audits");
//     } else {
//       score += 1;
//     }

//     // Backup
//     if (q4.includes("no") || q4.includes("manual")) {
//       risks.push("Weak or unreliable backup strategy");
//       recommendations.push("Implement automated and tested backup systems");
//     } else {
//       score += 1;
//     }

//     let maturity = "Low (1/5)";
//     if (score === 2) maturity = "Developing (2/5)";
//     if (score === 3) maturity = "Defined (3/5)";
//     if (score === 4) maturity = "Mature (4/5)";

//     const riskList = risks.map(r => `<li>${r}</li>`).join("");
//     const recList = recommendations.map(r => `<li>${r}</li>`).join("");

//     document.getElementById("output").innerHTML = `
//       <h2>IT Risk Assessment Report</h2>

//       <p><strong>Company:</strong> ${company}</p>
//       <p><strong>Industry:</strong> ${industry}</p>

//       <hr>

//       <h3>Risk Summary</h3>
//       <p>
//         Based on the provided inputs, the organization shows a ${maturity} level of IT control maturity.
//       </p>

//       <h3>Key Risks</h3>
//       <ul>${riskList || "<li>No major risks identified</li>"}</ul>

//       <h3>Recommendations</h3>
//       <ul>${recList || "<li>Maintain current controls and monitor regularly</li>"}</ul>

//       <h3>Maturity Level</h3>
//       <p><strong>${maturity}</strong></p>

//       <hr>
//       <p style="font-size:12px;opacity:0.7;">Generated by AuditReady AI</p>
//     `;

//   }, 1200);
// }