function generateReport() {

  const company = document.getElementById("company").value;
  const industry = document.getElementById("industry").value;

  // Step 1: Show AI thinking effect
  document.getElementById("output").innerText = "🔍 Analyzing your IT environment...";

  // Step 2: Simulate AI delay
  setTimeout(() => {

    // Step 3: Show structured professional report
    document.getElementById("output").innerHTML = `
      <h2>IT Risk Assessment Report</h2>

      <p><strong>Company:</strong> ${company}</p>
      <p><strong>Industry:</strong> ${industry}</p>

      <hr>

      <h3>Risk Summary</h3>
      <p>
        The organization demonstrates a moderate level of IT risk due to partial
        implementation of security controls and inconsistent governance practices.
      </p>

      <h3>Key Risks</h3>
      <ul>
        <li>Lack of strong access control mechanisms</li>
        <li>Absence of multi-factor authentication (MFA)</li>
        <li>Inconsistent audit and monitoring practices</li>
        <li>Weak or undefined backup and recovery strategy</li>
      </ul>

      <h3>Recommendations</h3>
      <ul>
        <li>Implement Role-Based Access Control (RBAC)</li>
        <li>Enable MFA across all critical systems</li>
        <li>Conduct periodic internal and external audits</li>
        <li>Establish automated and tested backup policies</li>
      </ul>

      <h3>Maturity Level</h3>
      <p><strong>Level 3.5/5 – Developing</strong></p>

      <hr>

      <p style="font-size: 12px; opacity: 0.7;">
        Generated by AuditReady AI
      </p>
    `;

  }, 1500); // 1.5 second delay for realism
}